version: "3.3"

services:
    db:
        image: postgres:13.4-buster
        env_file:
            - .env
        environment:
            - POSTGRES_DB=${DATABASE_NAME}
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASS}
            - TZ=${TIME_ZONE}
        ports:
            - ${EXTERNAL_DATABASE_PORT}:5432
        volumes:
            - db:/var/lib/postgresql/data
        # restart: always

volumes:
    db: